# Generated by Django 2.2.4 on 2019-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('wing', models.CharField(max_length=2)),
                ('nuber_of_seats', models.IntegerField()),
                ('nuber_of_computers', models.IntegerField()),
                ('additional_equipment', models.CharField(choices=[('BRAK', 'Brak'), ('STEROWNIKI', 'Sterowniki'), ('PRACOWNIA_FIZYCZNA', 'Pracownia fizyczna')], default='BRAK', max_length=50)),
            ],
        ),
    ]
