# Generated by Django 2.2.8 on 2020-01-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20191118_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='additional_equipment',
            field=models.CharField(choices=[('Brak', 'Brak'), ('Sterowniki', 'Sterowniki'), ('Pracownia fizyczna', 'Pracownia fizyczna')], default='BRAK', max_length=50),
        ),
    ]
