# Generated by Django 2.2.7 on 2019-12-04 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_start', models.DateField(default=datetime.date(2019, 12, 4))),
                ('season_end', models.DateField(default=datetime.date(2019, 12, 4))),
                ('summer_semester_start', models.DateField(default=datetime.date(2019, 12, 4))),
                ('summer_semester_end', models.DateField(default=datetime.date(2019, 12, 4))),
                ('winter_semester_starts', models.DateField(default=datetime.date(2019, 12, 4))),
                ('summer_semester_starts', models.DateField(default=datetime.date(2019, 12, 4))),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
    ]
