# Generated by Django 2.2.7 on 2019-12-04 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_season', '0002_auto_20191204_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationseason',
            name='season_end',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 10, 3, 16, 581284, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='season_start',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 10, 3, 16, 581257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='summer_semester_end',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 10, 3, 16, 581315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='summer_semester_start',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 10, 3, 16, 581303, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='summer_semester_starts',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 10, 3, 16, 581336, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='winter_semester_starts',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 10, 3, 16, 581326, tzinfo=utc)),
        ),
    ]
