# Generated by Django 2.2.7 on 2019-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_season', '0003_auto_20191204_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationseason',
            name='season_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='season_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='summer_semester_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='summer_semester_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='summer_semester_starts',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationseason',
            name='winter_semester_starts',
            field=models.DateField(),
        ),
    ]
