# Generated by Django 2.2.7 on 2019-12-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_season', '0004_auto_20191204_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationseason',
            old_name='summer_semester_starts',
            new_name='winter_semester_end',
        ),
        migrations.RenameField(
            model_name='reservationseason',
            old_name='winter_semester_starts',
            new_name='winter_semester_start',
        ),
    ]
