# Generated by Django 2.2.8 on 2020-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191118_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultations',
            field=models.TextField(default='asdsadsa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=123456789),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='roomNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
