# Generated by Django 2.2.8 on 2020-01-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200107_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consultations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
