# Generated by Django 2.2.8 on 2020-01-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200111_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='elo@op.pl', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
