# Generated by Django 2.2.4 on 2019-11-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_every_two_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='semester',
            field=models.CharField(choices=[('LETNI', 'Letni'), ('ZIMOWY', 'Zimowy')], default='ZIMOWY', max_length=255),
        ),
    ]
