# Generated by Django 2.2.7 on 2019-11-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20191123_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='semester',
            field=models.CharField(blank=True, choices=[('LETNI', 'Letni'), ('ZIMOWY', 'Zimowy')], default='ZIMOWY', max_length=255, null=True),
        ),
    ]
