# Generated by Django 2.2.7 on 2019-11-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20191123_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='is_every_two_week',
            new_name='is_every_two_weeks',
        ),
    ]
