# Generated by Django 2.2.8 on 2019-12-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20191123_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='semester',
        ),
    ]
