# Generated by Django 2.2.8 on 2020-01-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20200111_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='owner',
        ),
    ]
