# Generated by Django 2.2.8 on 2020-01-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20200111_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='owner',
            new_name='user',
        ),
    ]
